version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Data.Sqlite
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.Extensions.Logging
    versions:
    - 5.0.0
  - dependency-name: Microsoft.Extensions.FileSystemGlobbing
    versions:
    - 5.0.0
  - dependency-name: Microsoft.Extensions.DependencyInjection
    versions:
    - 5.0.1
  - dependency-name: Npgsql
    versions:
    - 5.0.3
  - dependency-name: Microsoft.Extensions.Configuration.Json
    versions:
    - 5.0.0
  - dependency-name: Microsoft.Extensions.Configuration.Abstractions
    versions:
    - 5.0.0
  - dependency-name: Microsoft.Extensions.Logging.Console
    versions:
    - 5.0.0
  - dependency-name: Moq
    versions:
    - 4.16.0
    - 4.16.1
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
