name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Build with dotnet
      run: dotnet build --configuration Release
    
    - name: Run Infer#      
      uses: microsoft/infersharpaction@v0.2
      id: runinfersharp
      with:
        binary-path: /DotnetMigrations/bin/Release/netcoreapp3.1
      
    - name: Infer# analysis results
      run: echo "${{ steps.runinfersharp.outputs.results }}"
